name: kpostal
description: Kpostal package can search for Korean postal addresses using Kakao postcode service. This package is inspired by Kopo package that is discontinued.
version: 0.5.1
homepage: https://github.com/tykann/kpostal

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_inappwebview: ^5.4.3+7
  flutter_inappwebview:
    git:
      url: https://github.com/VictorUvarov/flutter_inappwebview
      ref: ios-16-compile-issue
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/kakao_postcode_localhost.html
